### ISSUE TITLE
local host url in blog post "How this site is built"

### ISSUE THREAD

**Issue by callistusndemo** [holly-cummins/holly-cummins.github.io#1]
@holly-cummins, enjoyed reading your latest blog, [How this site is built](http://hollycummins.com/tech-stack/). Just an FYI there is a url in the Hosting section that is pointing to a local host. 

![local-url](https://user-images.githubusercontent.com/29136312/142258935-40d48e58-baec-4004-9463-a5af1c6bc01d.png)

Cheers

**Comment by holly-cummins** [comment]
Good spot, thanks! I've fixed that, and also more clearly linked to the starter for this site (https://github.com/holly-cummins/gatsby-platform/) and the live skeleton (http://gatsby-platform.hollycummins.com).
